### PR TITLE
Closes #240

### LINKED ISSUE #240: See points that others have created in the survey
Pins should be a different color, if someone else has added them.

### PR DESCRIPTION
**Pull request by kamicut**
Could you take a quick look for style @felskia ?

### CODE REVIEW

**Comment by felskia** [comment]
@kamicut is there an easy way to test this? Since I don't have anyone else using my setup I don't see how I'll be able to get other pins on the app.

**Comment by kamicut** [comment]
@felskia the way I've been doing it is syncing the current observations with the coordinator app, then wiping the phone using the AVD manager. This would force the simulator to acquire a new device id. When you sync the survey again you would have pins associated with the previous device.

**Comment by sethvincent** [comment]
It can also be tested by using two separate emulators.

**Comment by kamicut** [comment]
@sethvincent ah right, why didn't I think of that :sweat_smile:

**Pull request merged**
