### PR TITLE
Modify OSM.org XML import to be more reliable

### PR DESCRIPTION
**Pull request by noffle**
Hey all; sorry it's taken me so long to look into this. I'm really bummed that my quick-import hack idea ended up putting sync in such a fragile, unreliable state.

I was poking at it today and arrived on a compromise: the coordinator app stills sends a simple XML text stream over the pipe (fast!), but the collector app writes the batch of OSM elements to the osm-p2p-db *live*, rather than trying to go through the (extremely fragile) dance of shutting down the DB and doing offline inserts before spinning it all back up. This side steps all of the race conditions around the spin-down/spin-up of the osm-p2p-db, but still keeps the wire transfer part as fast as possible.

I've tested this on my laptop & device. It mechanically appears to work, but I'm not sure how to view the data I imported from OSM.org! I'm pretty sure I have an XML dump from NY City from the coordinator app, but when I pan over to New York I don't see anything but the mapbox vector tiles. This is made a bit tougher because the OSM.org map and download components of the collector app don't work for me (cc @dereklieu): the map stays blank (no errors), and when I hit the button to download the area, I see `Cannot read property 'unproject' of null` errors. I can create an issue /w full stacktrace in the coordinator app repo if you don't already know about this.

### CODE REVIEW

**Comment by noffle** [comment]
Addresses https://github.com/osmlab/field-data-collection/issues/180

**Comment by sethvincent** [comment]
@noffle Thanks! I think this is going to help.

I added a little commit removing `console.time` for now as it's not supported by react-native.

I'm looking for another way to have a timer, as that would be useful. This polyfill might be a good option: https://github.com/MaxGraey/react-native-console-time-polyfill

@mojodna @felskia y'all should try this out and see if it helps with issues you've seen.

**Comment by noffle** [comment]
@sethvincent Thanks for catching the `console.time` thing. Weird that it worked fine when I was testing it with a device.

**Comment by sethvincent** [comment]
@noffle I had this error come up when importing a small set of OSM data into an empty db: 

```
E/ReactNativeJS( 3474): Attempt to allocate Buffer larger than maximum size: 0x7fffffff bytes
W/ReactNativeJS( 3474): Unable to symbolicate stack trace: The stack is null
```

Happened a little while after the indexing started.

**Comment by noffle** [comment]
Did it prevent the sync & indexing from completing okay?

**Comment by sethvincent** [comment]
@noffle yeah, indexing never completed.

**Comment by sethvincent** [comment]
Though I don't get this every time. I'll try to figure out when it happens. Maybe if the OSM data includes a really big `way` or `relation`? Hard to tell what's going on without a stack trace 😞🙃.

**Comment by mojodna** [comment]
Visual stack trace, sans source map :-(

image
image
image
image

**Comment by mojodna** [comment]
This is the line that's triggering the `Buffer` error: https://github.com/substack/hyperlog-join/blob/master/index.js#L60

**Comment by mojodna** [comment]
Actually, it could be in either `hyperlog-join@1.3.1` (from `osm-p2p-observations`) or `hyperlog-join-2.0.0` (from `osm-p2p-db`).

**Comment by mojodna** [comment]
It's `2.0.0`.

**Comment by mojodna** [comment]
`key` (which is what's being converted to hex) is: `13067329334334044000`

**Comment by mojodna** [comment]
It's also an error under vanilla Node:

```
> Buffer(13067329334334044000)
RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at Buffer (buffer.js:78:19)
```

I'm looking for whatever's generating those keys next.

**Comment by mojodna** [comment]
https://github.com/substack/hyperlog-join/pull/2

**Comment by noffle** [comment]
Ah, thank you @mojodna for tracking this down!

i realize what happened on my end: the `hex2dec` function in `app/lib/osm-import.js` is outputting a `Number` instead of a `String`. This is my mistake. See my new commit to this branch that addresses it. I'm still 100% down with your PR to `hyperlog-join` though: it's good to be more thorough about type expectations.

**Comment by mojodna** [comment]
We're doubling up then; I already added a `toString` in ddfaeae0bb70b4f412dffa77537f5581f2439bb8

**Comment by noffle** [comment]
Whoops, I missed that. I nixed your commit, just because I'd rather address the issue at the function rather than the callsite. Thanks for your help on this @mojodna! :heart:

**Comment by mojodna** [comment]
It's not worth spending more time on, but `hex2dec` suggests that I'd get a decimal (number) out of that function; explicitly converting it to a string for the ID mapping makes more sense to me. Whatevs though, there are bigger fish to fry.

**Comment by noffle** [comment]
@mojodna yeah, I agree with you on that, now that I think some more about it. You're right: it's not a big deal, but *next time* I'll approach it differently.

**Pull request merged**
